# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QFrame#dibujo1{\n"
"background-color:rgb(60, 213, 255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dibujo1 = QtWidgets.QWidget(self.centralwidget)
        self.dibujo1.setGeometry(QtCore.QRect(99, 49, 621, 231))
        self.dibujo1.setMinimumSize(QtCore.QSize(0, 0))
        self.dibujo1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dibujo1.setStyleSheet("")
        self.dibujo1.setObjectName("dibujo1")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.boton1.setObjectName("boton1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 500, 91, 51))
        self.label1.setObjectName("label1")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.boton2.setObjectName("boton2")
        self.dibujo2 = QtWidgets.QWidget(self.centralwidget)
        self.dibujo2.setGeometry(QtCore.QRect(79, 319, 651, 181))
        self.dibujo2.setObjectName("dibujo2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton1.setText(_translate("MainWindow", "PushButton"))
        self.label1.setText(_translate("MainWindow", "TextLabel"))
        self.boton2.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
